# Generated by Django 4.0.5 on 2022-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishikawa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishikawa',
            name='analyse',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
