# Generated by Django 4.0.5 on 2022-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_prob_image'),
        ('ishikawa', '0002_ishikawa_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
        migrations.CreateModel(
            name='Main_oeuvre',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('analyse', models.CharField(max_length=500, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
        migrations.CreateModel(
            name='Matière',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
        migrations.CreateModel(
            name='Milieu',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
        migrations.CreateModel(
            name='Méthode',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
        migrations.DeleteModel(
            name='Ishikawa',
        ),
    ]
