# Generated by Django 4.0.5 on 2022-06-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_prob_image'),
        ('ishikawa', '0003_machine_main_oeuvre_matière_milieu_méthode_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='Macine',
        ),
    ]
