# Generated by Django 4.0.5 on 2022-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishikawa', '0006_cause_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause_machine',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
