# Generated by Django 4.0.5 on 2022-06-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishikawa', '0007_alter_cause_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause_milieu',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.milieu')),
            ],
        ),
        migrations.CreateModel(
            name='Cause_methode',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.méthode')),
            ],
        ),
        migrations.CreateModel(
            name='Cause_matiere',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.matière')),
            ],
        ),
        migrations.CreateModel(
            name='Cause_main',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, null=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.main_oeuvre')),
            ],
        ),
    ]
