# Generated by Django 4.0.5 on 2022-06-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objectif', models.IntegerField(null=True)),
                ('Output', models.IntegerField(null=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('heure', models.TimeField(auto_now=True, null=True)),
            ],
        ),
    ]
