# Generated by Django 4.0.5 on 2022-06-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id_prob', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('id_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.station')),
            ],
        ),
    ]
