# Generated by Django 4.0.5 on 2022-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_rename_id_prob_prob_id_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prob',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
