# Generated by Django 4.0.5 on 2022-06-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Down',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Durée', models.FloatField(null=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('heure', models.TimeField(auto_now=True, null=True)),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('id_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='station.station')),
            ],
        ),
    ]
