# Generated by Django 4.0.5 on 2022-06-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0002_rename_id_prob_prob_id_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Occurence', models.IntegerField(null=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('heure', models.TimeField(auto_now=True, null=True)),
                ('id_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.prob')),
            ],
        ),
    ]
