# Generated by Django 4.0.5 on 2022-06-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('Num_station', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.machine')),
            ],
        ),
    ]
