# Generated by Django 4.0.5 on 2022-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whys', '0011_why5_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why1_mac',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
