# Generated by Django 4.0.5 on 2022-06-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ishikawa', '0008_cause_milieu_cause_methode_cause_matiere_cause_main'),
        ('whys', '0017_why_mac_delete_why1_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why1', models.CharField(max_length=500, null=True)),
                ('why2', models.CharField(max_length=500, null=True)),
                ('why3', models.CharField(max_length=500, null=True)),
                ('why4', models.CharField(max_length=500, null=True)),
                ('why5', models.CharField(max_length=500, null=True)),
                ('cons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.cause_methode')),
            ],
        ),
        migrations.CreateModel(
            name='Why_mi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why1', models.CharField(max_length=500, null=True)),
                ('why2', models.CharField(max_length=500, null=True)),
                ('why3', models.CharField(max_length=500, null=True)),
                ('why4', models.CharField(max_length=500, null=True)),
                ('why5', models.CharField(max_length=500, null=True)),
                ('cons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.cause_milieu')),
            ],
        ),
        migrations.RenameModel(
            old_name='Why5_me',
            new_name='Why_mat',
        ),
        migrations.RemoveField(
            model_name='why1_mi',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why2_mac',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why2_mat',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why2_mi',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why3_mac',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why3_mat',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why3_mi',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why4_mac',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why4_mat',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why4_mi',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why5_mac',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why5_mat',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='why5_mi',
            name='cons',
        ),
        migrations.AlterField(
            model_name='why_mat',
            name='cons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ishikawa.cause_matiere'),
        ),
        migrations.DeleteModel(
            name='Why1_mat',
        ),
        migrations.DeleteModel(
            name='Why1_mi',
        ),
        migrations.DeleteModel(
            name='Why2_mac',
        ),
        migrations.DeleteModel(
            name='Why2_mat',
        ),
        migrations.DeleteModel(
            name='Why2_mi',
        ),
        migrations.DeleteModel(
            name='Why3_mac',
        ),
        migrations.DeleteModel(
            name='Why3_mat',
        ),
        migrations.DeleteModel(
            name='Why3_mi',
        ),
        migrations.DeleteModel(
            name='Why4_mac',
        ),
        migrations.DeleteModel(
            name='Why4_mat',
        ),
        migrations.DeleteModel(
            name='Why4_mi',
        ),
        migrations.DeleteModel(
            name='Why5_mac',
        ),
        migrations.DeleteModel(
            name='Why5_mat',
        ),
        migrations.DeleteModel(
            name='Why5_mi',
        ),
    ]
